### ISSUE TITLE
Estim signal stops when media changes while using sync media

### ISSUE THREAD

**Issue by 47dahc** [diglet48/restim#13]
In particular using VLC. Not sure about other media players. I have a bunch of short videos that I created funscripts to and converted to alpha/beta scripts using restim. I then add these videos to VLC playlist and play them randomly for a different CH type session every time. However, when a video ends and it loads the next video, Restim will load the scripts perfectly but, the estim signal stops and I have to select "Start" again. Not sure if this is by design, or is a bug? If by design, can we get an option to keep signal on when switching media?

**Comment by diglet48** [comment]
Sorry for the delay. This by design. I was concerned about safety issues when switching from a video with volume funscript to one without, this is easy to do accidentally and can result in a massive increase in volume.

I should change it so you can opt-out of this behavior so you can enjoy playlists of short videos, but haven't taken the time.

**Comment by diglet48** [comment]
This has been implemented a few versions ago :)
