### ISSUE TITLE
Feature request: Calibration reset

### ISSUE THREAD

**Issue by 47dahc** [diglet48/restim#5]
Feature request:
Would like to see a "Reset Defaults" for the 3-phase calibration window like 3-phase Adjust limits window has. I was doing a session and got all messed up with the levels. The previous session I did was awesome but for some reason this session had different feeling. So when I went to recalibrate, it got all out of whack. Had to come here to get an idea where the levels should be. A reset button would be quicker and not cause the loss of "mood".

**Comment by diglet48** [comment]
Sorry for the delay.

Do you mean reset it back to zero? That wouldn't be very useful because zero is almost never what you want.

Do you mean reset it back to the values of the previous session? That's potentially useful. I usually write down the final settings I used at the end of each session and there's a pretty big variation in settings even when I try to have the same placement. Can't really avoid making adjustments every session. Problem is that the software has no idea what the end of the session is and it would take a lot of UI work so users can tell the software to save these settings as defaults. Which users won't use due to post nut clarity. Sounds like more trouble / UI clutter than it's worth...

**Comment by 47dahc** [comment]
There were stock settings already in the program when I installed it. After doing the a calibration for one session which was amazing, a few days later I went to do another but the settings didn't feel as well. After trying to recalibrate, the numbers were way out of whack and nothing felt good. I had to come back here to see what the wiki had but even then, I don't think they were what was stock in a fresh install. So really, just a reset to stock, whatever that is.

**Comment by diglet48** [comment]
The defaults were 0/0/-0.7 in version 1.8, which was changed to 0/0/0 in version 1.9. It seems unlikely that these settings are any good.

I know calibration is difficult, but adding a button to reset them back to zero doesn't really fix anything.

**Comment by 47dahc** [comment]
Hmm. Maybe when I loaded 1.9 it took the settings I had already had in previous version. Pretty sure it wasn't 0/0/0. Guess I need to take notes...lol
